add_executable(
    ${CODAL_OUTPUT_NAME}
    ${SOURCE_FILES}
)

if("${INCLUDE_DIRS}" STRGREATER "")
    target_include_directories(${CODAL_OUTPUT_NAME} PUBLIC "${INCLUDE_DIRS}")
endif()

set_target_properties(${CODAL_OUTPUT_NAME} PROPERTIES SUFFIX "" ENABLE_EXPORTS ON)

# link the executable with supporting libraries.
target_link_libraries(
    ${CODAL_OUTPUT_NAME}
    ${CODAL_DEPS}
)

# import toolchain bin generation command
if(device_generate_bin)
    include(${TOOLCHAIN_FOLDER}/bin-generator.cmake)
endif()

# import toolchain hex generation command
if(device_generate_hex)
    include(${TOOLCHAIN_FOLDER}/hex-generator.cmake)
endif()

# import toolchain show build size command
if(device_show_size)
    include(${TOOLCHAIN_FOLDER}/size-info.cmake)
endif()

# post process command hook, depends on the hex file generated by the build system.
json_get_or_empty(device_post_process_depends device_json "post_process" "depends")
if("${device_post_process_command}" STRGREATER "" OR "${device_post_process}" STRGREATER "")

    if("${device_post_process}" STRGREATER "")
        set(POST_PROCESS_COMMAND ${device_post_process})
    else()
        set(POST_PROCESS_COMMAND ${device_post_process_command})
    endif()

    set(POST_PROCESS_DEPENDS "${device_post_process_depends}")

    # replace specific strings in the command, this gives users flexibility, they don't have to manually specify the location of files
    string(REPLACE "<OUTPUT_HEX_LOCATION>" ${PROJECT_SOURCE_DIR}/${CODAL_APP_OUTPUT_DIR}/${CODAL_OUTPUT_NAME}.hex  CODAL_POSTPROCESS_COMMAND ${POST_PROCESS_COMMAND})
    string(REPLACE "<OUTPUT_HEX_DESTINATION>" ${PROJECT_SOURCE_DIR}/${CODAL_APP_OUTPUT_DIR} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})
    string(REPLACE "<OUTPUT_HEX_NAME>" ${CODAL_OUTPUT_NAME} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})

    string(REPLACE "<OUTPUT_BIN_LOCATION>" ${PROJECT_SOURCE_DIR}/${CODAL_APP_OUTPUT_DIR}/${CODAL_OUTPUT_NAME}.bin  CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})
    string(REPLACE "<OUTPUT_BIN_DESTINATION>" ${PROJECT_SOURCE_DIR}/${CODAL_APP_OUTPUT_DIR} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})
    string(REPLACE "<OUTPUT_BIN_NAME>" ${CODAL_OUTPUT_NAME}.bin CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})

    string(REPLACE "<OUTPUT_ELF_LOCATION>" ${PROJECT_SOURCE_DIR}/build/${CODAL_OUTPUT_NAME} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})
    string(REPLACE "<OUTPUT_ELF_DESTINATION>" ${PROJECT_SOURCE_DIR}/${CODAL_APP_OUTPUT_DIR} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})
    string(REPLACE "<OUTPUT_ELF_NAME>" ${CODAL_OUTPUT_NAME} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})

    string(REPLACE "<CODAL_APP_OUTPUT_DIR>" ${PROJECT_SOURCE_DIR}/${CODAL_APP_OUTPUT_DIR} CODAL_POSTPROCESS_COMMAND ${CODAL_POSTPROCESS_COMMAND})

    #convert to a command
    separate_arguments(FINAL_COMMAND UNIX_COMMAND ${CODAL_POSTPROCESS_COMMAND})

    # execute
    if(POST_PROCESS_DEPENDS STREQUAL "ELF")
        add_custom_command(
            TARGET ${CODAL_OUTPUT_NAME}
            COMMAND ${FINAL_COMMAND}
            DEPENDS  ${CODAL_OUTPUT_NAME}
            WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
            COMMENT "Executing post process command"
        )
    elseif(POST_PROCESS_DEPENDS STREQUAL "HEX")
        add_custom_command(
            TARGET ${CODAL_OUTPUT_NAME}_hex
            COMMAND ${FINAL_COMMAND}
            DEPENDS  ${CODAL_OUTPUT_NAME}
            WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
            COMMENT "Executing post process command"
        )
    else()
        #by default post process should depend on hex
        add_custom_command(
            TARGET ${CODAL_OUTPUT_NAME}_bin
            COMMAND ${FINAL_COMMAND}
            DEPENDS  ${CODAL_OUTPUT_NAME}
            WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
            COMMENT "Executing post process command"
        )
    endif()

endif()