name: CI

on:
  push:
    branches:
      - main
      - staging
    paths-ignore:
      - '**.md'
      - 'doc/**'

  pull_request:
    branches:
      - main
      - staging
    paths-ignore:
      - '**.md'
      - 'doc/**'

jobs:
  build-linux-amd64:
    name: "linux x86_64"
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/attila-lendvai/microbit-ci:amd64
      options: --init

    steps:
      - name: System info
        run: |
          echo "===== OS Info ====="
          uname -a
          sw_vers || lsb_release -a || cat /etc/os-release || true
          echo "===== CPU Info ====="
          uname -m
          sysctl -n machdep.cpu.brand_string || lscpu || true
          echo "===== Environment ====="
          env

#      - name: Calm down Git
#        run: git config --global --add safe.directory /__w/maru/maru

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - run:  arm-none-eabi-gcc --version

      - run:  ./build.py
